---
title: "Aula 6 - Equilíbrio de Nash"
author: "Manoel Galdino"
date: "2023-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aplicações de Equilíbrio de Nash

Quando as pessoas pensam em eleições, muitos acreditam que políticos anunciam as plataformas que acreditam, e eleitores escolhem a que preferem. Contudo, na ciência política é comum assumir que, mesmo que políticos se preocupem com suas plataformas serem implementadas, sabem que para isso primeiro precisam ganhar eleições. Portanto, seja porque estão preocupados apenas com o poder ou porque precisam estar preocupados com o poder para implementar plataformas, o fato é que uma supoição comum é assumir que políticos maximizam suas chances de serem eleitos. Essa é a base do modelo discutido por Hotelling (1929). Após contribuições de Duncan Black (Black,
1948) e Anthony Downs (Downs, 1957), a ideia entrou definitvamente na Ciência Política e ficaria conhecida como Teorema do Eleitor Mediano. 

O modelo do Hotelling tem inspiração em um modelo de competição espacial entre firmas. Ele desenvolve um jogo em dois estágios, em que duas firmas, competindo em uma rua, devem escolher sua localização geográfica no primeiro estágio, e em seguida os consumidores escolhem onde vão comprar os produtos, levando em consideração não apenas o preço dos produtos, mas o custo do transporte. E ele acha um equilíbrio de Nash (sem usar esse termo, obviamente) em que as empresas tendem a se concentrar no meio da rua. E ele notou que essa ideia poderia ser aplicada par competição política entre partidos.  Nós apresenramos aqui uma versão simplificada da ideia do Hotelling e do Teorema do Eleitor Mediano.

Suponha dois políticos, que se importam apenas em ganhar a eleição. Existem 101 eleitores, com preferências uniformimente distribuídas em uma úncia dimensão do espectro político-ideológico. Em particular, suponha que oeleitor mais a esquerda está na posição -50, em seguida -49 e assim por diante, cada um com um número inteiro, até a extrema-direita, +50.

Cada candidato $i$ escolhe uma plataforma $a_i$ no espectro político-ideológico $[-50, -49, ..., +49, +50]$. Cada eleitor escolhe a plataforma mais próxima da sua posição ideal. Por exemplo, de candidato 1 anuncia -20 como plataforma e o candidato 2 anuncia 31, o eleitor mais perto de -20 do que de 31 vota por 1, enquanto quem estiver mais perto de 31 vota por 2.

# determinar os eleitores pivot do exemplo.

É eleito quem obtiver mais voto. Como há um número ímpar de eleitores, a menos que alguém seja indiferente, não há empate. Se alguém for indiferente, o eleitor não vai votar e há um empate.
A melhor resposta do jogador $i$ é:
Se $j$ escolher uma plataforma $a_j > 0$, então $a_i = a_j$ ou $a_i = -a_j$ e dá um empate. Se $i$ escolher $a_i > a_j$ ou $a_i < -a_j$, perde com certeza. E escolhendo entre $a_i = a_j -1$ e $a_i = -a_j + 1$ irá ganhar com certeza. $a_i \in [-a_j + 1, a_j -1]$. Por um argumento similar se $a_j < 0$, temos que a estratégia vencedora é no intervalo $a_i \in [a_j + 1, -a_j -1]$. Por fim, a melhor resposta para $a_j = 0$ é $a_i = 0$.
Como é tudo simétrico, as melhores respostas de cada jogador são similares.

Existe um único equilíbrio de Nash, em que ambos candidatos jogam (0,0), que é o centro do espectro político. Essa é a base para o teorema do eleitor mediano, presente já no trabalho do Hotelling.

# Incerteza, risco e utilidade esperada

A introdução de probabilidades traz incerteza para nossos jogos. Por isso é importante entender como nossa teortia de comportamento racional pode se modificar na presença de incerteza.

A ideia da incerteza foi inicialmente abordada com a ideia de calcular o valor esperado de ações e escolher aquela ação que rende o maior valor esperado. Considere o seguinte jogo. Após responder várias perguntas corretas, uma pessoa em um programa de TV tem a seguinte escolha para fazer:
 a) será jogada uma moeda. Se cair coroa, ganha 100 mil reais. Se der cara, não ganha nada.
 b) Escolher entre três envelopes, cada um contém prêmios no valor de 90 mil reais, 30 mil reais e 15 mil reais. Qual estratégia ele deve escollher?
 
 O valor esperado de cada ação pode ser calculado da seguinte forma:
 a) $VE(A) = 100000*.5 + 0*.5 = 50.000,00$
 b) $VE(B) = 90000*(1/3) + 30000*(1/3) + 15000*(1/3) = 30000 + 10000 + 5000 = 45000$
 A pessoa deveria, portanto, escolher A, pois em média paga mais que do que a opção B.
 Uma justificativa para a ideia de maximizar o valor esperado é a seguinte. A pessoa se defronta com várias decisões em sua vida que possuem riscos. Pode comprar um carro com algum opcional de segurança que reduz seu risco de vida em acidentes, se vai atravessar fora da faixa e pedestre, se anda de moto, se sai na chuva em dia de raios etc. Cada decisão dela tem um risco e se escolher sempre maximizando a utilidade esperada, na média de longo prazo terá um retorno maior.
 
 Um problema da abordagem de maximizar o valor esperado é ilustrado pelo Paradoxo de São Petersburgo. Considere o seguinte jogo. Uma moeda é jogada, se o resultado é coroa, o jogador é pago 1 real e o jogo acaba. Se der cara, o jogo continua e uma moeda é novamente lançada. Se der coroa, recebe dois reais e o jogo acaba. Se der cara, o jogo continua e uma moeda é novamente lançada. Se der coroa, o jogador ganha 4 reais e o jogo acaba. Se der cara, o jogo continua, e assim indefinidamente, sempre dobrando o valor pago até o momento em que der cara.
 
 Suponha que a casa tem fundos ilimitados. Qual o valor esperado desse jogo? Ou, colocando de outro modo, quanto um jogador racional (no sentido de maximizar valor esperado) deveria pagar para ter o privilégio de jogar esse jogo?
 O jogo basicamente tem a seguinte configuração. A casa paga 1 real com probabiliade 50%, 2 reais com probabilidade 25%, 4 reais com prob. 1/8 e assim por diante:
 $VE(jogo) = 1*(1/2) + 2*(1/4) + 4*(1/8) + ...$
 
 Veja que essa soma infinita é equivalente a:
 
  $VE(jogo) = 1/2 + 2*/4 + 4/8 + ... = 1/2 + 1/2 + 1/2 + ...$

O que dá uma soma infinita.

Usando nossa lógica de escolher ações cujo valor esperado é maior, entre a alternativa de pagar toda a fortuna de uma pessoa para jogar o jogo e não jogar e preservar a forturna, pagar a fortuna dá um valor esperado maior, pois infinito menos uma quantia finita é ainda infinito.

Obviamente, não faz sentido escolher jogar esse jogo pagando toda a sua fortuna, pois na prática em algum momento a pessoa irá perder e antes de recuperar o valor de sua forturna.

Naturalmente, a questão seguinte a se perguntar é: podemos encontrar algum outro princípio para fundamentar a decisão sob incerteza?

Daniel Bernoulli, matemático, percebeu que o valor monetário é diferente a depender de quanto dinheiro você tem. O valor de mil reais para uma pessoa pobre é diferente do valor de mil reais para uma pessoa rica. Obviamente podemos supor que mais dinheiro é preferido a menos, porém não de maneira linear. Bernoulli sugeriu uma "lei da utilidade decrescente", como ficou conhecida depois, segundo a qual cada real adicional gera um pouco menos de utilidade. Mais ainda, ele propôs que a relação entre dinheiro e utilidade deveria ser logarítmica, o que implica que mudanças percentuais no dinheiro implicam mudanças iguais na utilidade.

Duas críticas forma feitas à proposta de Bernoulli. Em primeiro lugar, a arbitrariedade do uso de logarítmo. Em segundo lugar, como medir utilidades? Nós já vimos que podemos trabalhar com utilidades ordinais. Mas cardinais, é bem mais complicado.

Tivemos de esperar até o trabalho de von Neumann e Morgenstern Game Theory and EconomicBehavior (1944) para haver uma reabilitação das ideias propostas por Bernoulli. A ideia chave de VNM é que é possível estimar a intensidade de preferências em uma escala intervalar (em que os pontos máximos e mínimos são arbitŕarios, como na escala de celcius e farenheit) a partir da elicitação de preferências sobre loterias. Com representações numéricas de utilidade, podemos calcular a utilidade esperada (à maneira do valor esperado), exceto que a utilidade marginal pode ser decrescente e, portanto, evitar o paradoxo de São Petersburgo.

Vamos ver como funciona por meio do seguinte exemplo.

Suponha que uma loteria tem quatro possíveis prêmios: $x_1, x_2, x_3, x_4$. Suponha que os prêmios foram ordenados em ordem ascendente de preferência, isto é, $x_4 \succ x_3 \succ x_2 \succ x_1$. Agora, atribua valores de utilidade arbitrários para o prêmio mais desejado e o menos desejado. Digamos: $u(x_4) = 1$ e $u(x_1) = 0$.

Quaisquer outros números funcionariam, mas é conveniente matematicamente (já veremos o porquê) usar zero e um. Usando esses dois valores de utilidade como ancoragem, o ponto do teorema de VNM é que existe uma forma garantida de atribuir utilidades numéricas para as preferências de cada um dos prêmios, de forma que podemos trabalhar com o caĺculo de utilidade esperada. O procedimento é o seguinte. Considere qualquer outro prêmio (por exemplo, $x_2$). Pergutamos então a cada jogador qual a probabilidade $p_2$ que tornaria ela indiferente entre ganhar $x_2$ com certeza e $x_4$ com probabilidade $p_2$ e $x_1$ com probabilidade $1 - p_2$. Veja que quanto mais valioso for $x_2$, maior deve ser $p_2$, a chance de ganhar $x_4$ o prêmio mais valorizado, para que a pessoa aceite trocar algo certo por aldo duvidoso. Assim, $p_2$ mede a desejabilidade do prêmio $x_2$.
A gente repete esse experimento com $x_3$ e assim teremos uma medida da desejabilidade de todos os prêmios.

E VNM definem a utilidade de cada prêmio como a aposta (loteria)que cada jogador considera igualmente desejável ao prêmio:

$u(x_i) = p_i*x_n + (1-p_i)*x_1$
No no caso:
$u(x_i) = p_i*1 + (1-p_i)*0 = p_i$

Ao escolher os valores máximos e mínimos da utilidade de maneira conveniente, as probabilidades passam a medir a desejabilidade diretamente de cada prêmio. Temos portanto números para as utilidades que não são apenas ordinais, mas cardinais.

Eu sei que nós gastamos muito tempo repetindo e enfatizando que a teoria da utilidade tratava apenas de representar preferências ordinais e, portanto, os números eram completamente arbitrários. Agora não, apenas os pontos máximos e mínimos são arbitrários, mas todos os demais são derivados por esse experimento mental. 

Na verdade, para ser mais preciso, o que VNM mostram é que se alguns axiomas forem satisfeitos, então agentes racionais se comportatão como se tivessem respondido a essas perguntas desse experimento. Mas não precisam de fato fazer esse experimento para se comportarem desse jeito. Mais ainda, em situações de incerteza, agentes racionais escolherão o que maximizar sua utilidade esperada.

A Teoria da Utilidade Esperada, portanto, ajuda a explicar porque pessoas contratam seguros ou apostam em loterias como a mega-sena. Embora o valor esperado seja negativo de ambas as escolhas, as pessoas possuem utilidades distintas de cada opção (jogar ou não jogar, contratar ou não-contratar seguro).

# Aversão a risco

Tipicamente as pessoas são avessas ao risco. No contexto da utilidade esperada, isso quer dizer que as pessoas preferem um payoff certo a uma aposta justa. Em outras palavras, se eu oferecer uma escolha entre ficar como está ou uma aposta em que você ganha mil reais se der cara, paga mil reais se der coroa, as pessoas tendem a preferir a primeira opção, ainda que o valor esperado seja igual. Se vocÇe for indiferente entre as duas opções, dizemos que você é neutro ao risco. E se prefere a aposta, você é amante do risco.

Tipicamente em modelos na ciência política, assume-se neutralidade ao risco ou aversão ao risco. Aversão ao risco é visto como a suposição mais aceitável e neutralidade ao risco é suposta apenas quando é mais fácil a matemática e a conclusão não muda se supusermos aversão ao risco.


# Teoria e Prática

Muitos testes foram feitos para verificar se o comportameto das pessoas em situações experimentais condizem com o previsto pela TUE. Em particular, Tversky and Kanheman realizaram uma série de experimentos. Vamos apresentar um deles aqui.

"Suponha que o Brasil está se preparando para um surto de uma doença que surgiu em outro país e a expectativa é que a doença matará 600 pessoas se nada for feito. Dois programas alternativos para combater as doenças foram pensados. Assuma que as exatas consequências científicas dos programas são como seguem:

1. 
Programa A: 200 pessoas serão salvas.
Programa B: Há uma probabilidade de $1/3$ que 600 pessoas serão salvas, e uma probabilidade de $2/3$ que nenhuma pessoa será salva.


72% escolherão A e 28% B
2. 
Programa C: 400 pessoas morrerão.
Programa D: Há uma probabilidade de $1/3$ que ninguém morrerá, e uma probabilidade de $2/3$ que 600 pessoas morrerão.

Já nesse cenário, 78% preferem D e 22% preferem C.

# Preferências sobre loterias

Já que estamos falando de loterias em nossa definição, é importante fazer um detour para explicar o conceito de loterias e preferências sobre loterias

Uma loteria existe quando eu tenho payoffs que têm um componente aleatório. A mega-sena paga alguns milhões de reais com uma dada probabilidade, e zero reais com outra probabilidade.

Mais formalmente:
Definição 6.2. Uma loteria simples sobre resultados $X = {x_1, x_2, ..., x_n}$ é definida como a distribuição de probabilidade $p = (p(x_1), p(x_2), ..., p(x_n))$, em que $p(x_k) \ge 0$ é a probabilidade de que $x_k$ ocorra e $\Sigma_{k=1}^n x_k = 1$.
