---
title: "Lista de exercícios 4 - solução"
author: "Manoel Galdino"
date: "2023-04-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Para os jogos especificados nos exercícios 1, 3, 4 , 5, 6, 7, 8 , 9 e 10 da lista 3, verifique se existe equilíbrio de Nash (em estratégias puras) e aponte qual é ou quais são os equilíbrios de Nash, se houver mais de um.


Resposta:

1.1.
Para o DP, CC é um ENEP, pois é a melhor resposta de ambos os jogadores ao queo outro está jogando.

Para o Bach e Stravinsky, temos dois ENEP: (B,B) e (S,S).

Para o Chicken, também temos dois ENEP: (D, ND) e (ND, D)

Para o Stag Hunt, temos (Cervo, Cervo) e (Lebre, Lebre).

3. Na matriz resultante de EIESD, temos dois ENEP: (Baixo, Esquerda) e (Baixo, Direita).

4. (Baixo, Esquerda) e (Baixo, Direita).

5. (Baixo, Esquerda), (Baixo, Centro) e (Alto, Direita)

6. Não há ENEP.

7.  Temos quatro ENEPs: (NC, C, C), (C, NC, C), (C,C, NC) e (NC, NC, NC). Ou seja, ter um não contribuindo e dois contribuindo é ENEP, porque ninguem pode melhorar (deixar de contribuir diminui o Payoff de quem estava contribuindo, e quem nã oestaa contribuindo também tem seu payoff diminuído). E quando ninguém contribui, pois não há incentivo individual a contribuir (mudar sua estratégia), já que o iluminação continuará sem ser instalada se apenas uma jogadora mudar unilateralmente.


8. Veja que não sensacionalista é estritamente dominada para todos os jogadores por sensacionalista. Logo, o único ENEP é (S, S, S), indicando sensacionalista por S.

9. Veja que 2 é estritamente dominada por 4 para ambas jogadoras. Logo, podemos eliminá-la do jogo. Na matriz resultante, 5 é estritamente dominada. Logo, (4,4) é o único ENEP.

10. Para 1, 500 é estritamente dominada por 400, logo, podemos eleiminá-la. Na matriz resultante, 500 é estritamente dominada por 400 para 2 e podemos também eliminá-la. OS ENEPS são: (400, 400), (300, 300) e (200, 200), 

2. Jogo do Ultimato. Considere o seguinte jogo com duas jogadoras (1 e 2). A jogadora 1 recebe 10 reais e deve decidir como dividir o dinheiro entre ela e a jogadora 2, entre números inteiros de 0 a 10 reais. Uma vez que ela decida uma divisão, faz uma oferta para a jogadora 2, que deve decidir se aceita ou não. Caso ela aceite, o jogo acaba com a divisão proposta. Caso ela rejeite, o jogo acaba com as jogadoras levando nada. Suponha que a preferência das jogadores pode ser captada pela seguinte função de utilidade: $u_i(s_1, s_2) = s_i$ se a proposta for aceita e $0$ se não for aceita. Veja que a jogadora 1 possui muitas estratégias (132 no total, verifique esse número), dada pelas combinações de propostas possíveis cuja soma é $\le 10$. Já a jogadora 2 pode apenas escolher entre aceitar a proposta (sim) ou rejitá-la (não). Logo, se a jogadora 1 propõe uma divisão 7 reais para ela e 3 reais para a jogadora 2 e esta aceita, então $u_1((7,3), sim) = 7$ e $u_2((7,3), "sim") = 3$.

a) Nesse jogo, explique porque a proposta (10, 0) é um equilíbrio de Nash. Explique também porque ele é um equilíbrio instável (não robusto a pequenas variações no pyaoff de 2), considerando a alternativa para a jogadora 2.

R. 1 obviamente não pode melhorar, pois 10 é o máximo. E dois, ao rejeitar a proposta, ficará com o mesmo payoff, portanto, tampouco pode melhorar, configurando assim um equilíbrio de Nash.

O equilíbrio não é robusto porque se 1 perder um mínimo de utilidade que seja por receber uma proposta tão desigual, ela prefere não aceitar a proposta.

b) Se o menor número possível for 1 real (em vez de zero) e o máximo 9 reais, qual o equilíbrio de Nash?

R. (9, 1).

c) Se voce fosse a jogadora 2 e recebesse a oferta do equilíbrio de Nash do jogo da letra b, aceitaria ou não? Justifique sua resposta.

Aqui é uma resposta pessoal, e toda resposta é válida.

c) Se você fosse a jogadora 1, faria uma oferta diferente da oferta de equilíbrio de Nash? Se sim, qual? Justifique sua resposta.

Aqui é uma resposta pessoal, e toda resposta é válida.

3. Jogo do ditador. Considere o seguinte jogo, uma variação do jogo do ultimato. A jogadora 1 recebe 10 reais e deve decidir quanto dividir entre ela e a jogadora 2. Uma vez feita a decisão de divisão, o jogo acaba, com a divisão proposta pela jogadora 1 (ditadora).

a) Quais as estratégias da jogadora 1 e 2?

R. Seja $x$ o valor para a jogadora 1, e $10 - x$ para a jogadora 2. Então, 

$S_1 = (x, 1-x), x \in \{10, 9, 8, 7, 6, 6, 4, 3, 2 , 1, 0\}$

Como 2 não faz nada, não possui estratégia. O que pode ser representado pelo conjunto vazio.

R. $S_2 = \{\phi\}$

b) Como você escreveria a função de utilidade das jogadoras?

R. $u_1(s_1) = x$ e $u_2(s_1) = 1-x$

c) Qual o equilíbrio de Nash desse jogo?

R. (10, 0).

d) Se você fosse a jogadora 1, faria uma oferta diferente da oferta de equilíbrio de Nash? Se sim, qual? Justifique sua resposta.

Aqui é uma resposta pessoal, e toda resposta é válida.

e) Em estudos experimentais (Oosterbeek et. al., 2004), a oferta média das jogadoras 1 no jogo do ultimato é de 40% do total (no caso do nosso jogo, 4 reais). Já estudos experimentais do jogo do ditador (Engel, 2011), a oferta média é de 28%, que no nosso caso seria aproximadamente 3 reais. Uma das explicações sugeridas para a oferta de 40% no jogo do ultimato é medo de que a outra pessoa não seja racional (ou não tenha preferências tais como a sugerida pela função utilidade do exercício 2) e, por isso, dariam uma oferta mais elevada do que a do equilíbrio de Nash para evitar o risco de acabarem sem nada. Nesse caso, a jogadora 1 teria preferências como a da função utilidade do exercício 2, mas não saberia se a jogadora 2 também teria uma função utilidade assim. Como você interpreta essa explicação diante dos resultados experimentais do jogo do ditador?

R. Como no jogo do ditador não há esse medo, essa explicação não explica boa parte das ofertas feitas.
Referências

Engel, C. (2011). Dictator games: A meta study. Experimental economics, 14, 583-610.

Oosterbeek, H., Sloof, R., & Van De Kuilen, G. (2004). Cultural differences in ultimatum game experiments: Evidence from a meta-analysis. Experimental economics, 7, 171-188.